export const ADD_SLIDE = 'ADD_SLIDE';
export const DELETE_SLIDE = 'DELETE_SLIDE';
export const TOGGLE_FULLSCREEN_MODE = 'TOGGLE_FULLSCREEN_MODE';
export const ADD_PLUGIN_TO_CURRENT_SLIDE = 'ADD_PLUGIN_TO_CURRENT_SLIDE';
