export const ADD_SLIDE = 'ADD_SLIDE';
export const DELETE_SLIDE = 'DELETE_SLIDE';
export const TOGGLE_FULLSCREEN_MODE = 'TOGGLE_FULLSCREEN_MODE';
export const RIGHT_ARROW_NEXT = 'RIGHT_ARROW_NEXT';
export const LEFT_ARROW_PREV = 'LEFT_ARROW_PREV';
export const ADD_PLUGIN_TO_CURRENT_SLIDE = 'ADD_PLUGIN_TO_CURRENT_SLIDE';

export const GO_TO_SLIDE = 'GO_TO_SLIDE';

// TextBox plugin actions
export const UPDATE_TEXTBOX_TEXT = 'UPDATE_TEXTBOX_TEXT';
export const UPDATE_CURRENT_SLIDE = 'UPDATE_CURRENT_SLIDE';

// OptionsBar
export const SET_NEW_ACTIVE_PLUGIN = 'SET_NEW_ACTIVE_PLUGIN';

// CodeEditor plugin actions
export const UPDATE_CODEEDITOR_CODE = 'UPDATE_CODEEDITOR_CODE';