export const ADD_SLIDE = 'ADD_SLIDE';
export const DELETE_SLIDE = 'DELETE_SLIDE';
export const TOGGLE_FULLSCREEN_MODE = 'TOGGLE_FULLSCREEN_MODE';
export const RIGHT_ARROW_NEXT = 'RIGHT_ARROW_NEXT';
export const LEFT_ARROW_PREV = 'LEFT_ARROW_PREV';