export const GO_TO_SLIDE = 'GO_TO_SLIDE';
export const LEFT_ARROW_PREV = 'LEFT_ARROW_PREV';
export const RIGHT_ARROW_NEXT = 'RIGHT_ARROW_NEXT';
export const SAVE_LAST_SLIDE_DIMENSION = 'SAVE_LAST_SLIDE_DIMENSION';
export const SET_ACTIVE_PLUGIN = 'SET_ACTIVE_PLUGIN';
export const TOGGLE_FULLSCREEN_MODE = 'TOGGLE_FULLSCREEN_MODE';
export const UPDATE_SLIDES_DIMENSION = 'UPDATE_SLIDES_DIMENSION';
